services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - wordpress
    restart: unless-stopped

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress-data:/var/www/html
    depends_on:
      - mariadb
    restart: unless-stopped

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/wordpress
      o: bind

  mariadb-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/mariadb
      o: bind

networks:
  inception:
    driver: bridge